set(KOMPEXSQLITE_HEADER_FILES kompex/KompexSQLiteDatabase.h)

FIND_PATH(KOMPEXSQLITE_INCLUDE_DIR ${KOMPEXSQLITE_HEADER_FILES}
	/usr/include
    /usr/local/include
    /opt/include
    /opt/kompex/include)

FIND_LIBRARY(KOMPEXSQLITE_LIBRARY
    NAMES kompex-sqlite-wrapper
	PATH_SUFFIXES lib64 lib
	PATHS /usr/local
          /opt
          /opt/kompex)
		  
GET_FILENAME_COMPONENT(KOMPEXSQLITE_LIBRARY_DIR ${KOMPEXSQLITE_LIBRARY} PATH)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(KOMPEXSQLITE DEFAULT_MSG
    KOMPEXSQLITE_LIBRARY KOMPEXSQLITE_INCLUDE_DIR)

if (KOMPEXSQLITE_FOUND)
    message(STATUS "found KompexSqlite: ${KOMPEXSQLITE_LIBRARY} ${KOMPEXSQLITE_INCLUDE_DIR}")
endif (KOMPEXSQLITE_FOUND)

mark_as_advanced(KOMPEXSQLITE_LIBRARY KOMPEXSQLITE_INCLUDE_DIR)

SET(KOMPEXSQLITE_INCLUDE_DIRS ${KOMPEXSQLITE_INCLUDE_DIR})
SET(KOMPEXSQLITE_LIBRARYS ${KOMPEXSQLITE_LIBRARY})