#find LOG4CPLUS

SET(YAMLCPP_HEADER_FILE yaml-cpp/yaml.h)

FIND_PATH(YAMLCPP_INCLUDE_DIR ${YAMLCPP_HEADER_FILE}
	/usr/local/include
    /usr/include
	/opt/yaml/include
  )
mark_as_advanced(YAMLCPP_INCLUDE_DIR)

FIND_LIBRARY(YAMLCPP_LIBRARY
   NAMES yaml-cpp
   PATH_SUFFIXES lib64 lib
   PATHS
	/usr/local
	/usr
	/opt/yaml)
mark_as_advanced(YAMLCPP_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(YAMLCPP DEFAULT_MSG
    YAMLCPP_LIBRARY YAMLCPP_INCLUDE_DIR)

if (YAMLCPP_FOUND)
    message(STATUS "found YAML-CPP: ${YAMLCPP_LIBRARY}")
	add_definitions(-DHAS_YAMLCPP)
endif (YAMLCPP_FOUND)

SET(YAMLCPP_INCLUDE_DIRS ${YAMLCPP_INCLUDE_DIR})
SET(YAMLCPP_LIBRARYS ${YAMLCPP_LIBRARY})